[package]
name = "julia"
version = "0.1.0"
authors = ["rambip"]
edition = "2018"

[lib]
crate-type = ["cdylib"]


[dependencies]
js-sys = "0.3.3"
wasm-bindgen = "=0.2.83"

[dependencies.web-sys]
version = "0.3.3"
features = [
        'ImageData',
        'CanvasRenderingContext2d',
]
